import type { Spec } from "@json-render/react";
import type {
  DashboardRecord,
  DashboardSummary,
} from "@posthog/core/canvas/dashboardSchemas";
import type { FreeformVersion } from "@posthog/core/canvas/freeformSchemas";
import { useHostTRPC } from "@posthog/host-router/react";
import { useCanvasChatStore } from "@posthog/ui/features/canvas/stores/canvasChatStore";
import { useDashboardEditStore } from "@posthog/ui/features/canvas/stores/dashboardEditStore";
import { toast } from "@posthog/ui/primitives/toast";
import { logger } from "@posthog/ui/shell/logger";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "@tanstack/react-router";
import { useCallback } from "react";

const log = logger.scope("dashboards");

/** Saved dashboards for a channel (file-backed, generated by json-render). */
export function useDashboards(channelId: string | undefined): {
  dashboards: DashboardSummary[];
  isLoading: boolean;
} {
  const trpc = useHostTRPC();
  const { data, isLoading } = useQuery(
    trpc.dashboards.list.queryOptions(
      { channelId: channelId ?? "" },
      { enabled: !!channelId, staleTime: 5_000 },
    ),
  );
  return { dashboards: data ?? [], isLoading };
}

/** A single saved dashboard record (spec + metadata). */
export function useDashboard(id: string | undefined): {
  dashboard: DashboardRecord | null | undefined;
  isLoading: boolean;
  isFetching: boolean;
} {
  const trpc = useHostTRPC();
  const { data, isLoading, isFetching } = useQuery(
    trpc.dashboards.get.queryOptions(
      { id: id ?? "" },
      { enabled: !!id, staleTime: 5_000 },
    ),
  );
  return { dashboard: data, isLoading, isFetching };
}

/** Save (update) + fork (create) mutations, invalidating the list + record. */
export function useDashboardMutations() {
  const trpc = useHostTRPC();
  const queryClient = useQueryClient();

  const invalidate = () => {
    void queryClient.invalidateQueries(trpc.dashboards.list.pathFilter());
    void queryClient.invalidateQueries(trpc.dashboards.get.pathFilter());
  };

  const save = useMutation(
    trpc.dashboards.update.mutationOptions({ onSuccess: invalidate }),
  );
  const create = useMutation(
    trpc.dashboards.create.mutationOptions({ onSuccess: invalidate }),
  );
  const remove = useMutation(
    trpc.dashboards.delete.mutationOptions({ onSuccess: invalidate }),
  );
  const saveFreeform = useMutation(
    trpc.dashboards.saveFreeform.mutationOptions({ onSuccess: invalidate }),
  );
  const ensureHome = useMutation(
    trpc.dashboards.ensureHomeCanvas.mutationOptions({
      onSuccess: () => {
        invalidate();
        // The folder now carries homeCanvasId; refresh the channel list so the
        // sidebar/name-click can route straight to it next time.
        void queryClient.invalidateQueries({ queryKey: ["canvas-channels"] });
      },
    }),
  );

  return {
    saveDashboard: (id: string, spec: Spec | null, name?: string) =>
      save.mutateAsync({
        id,
        spec: spec as Record<string, unknown> | null,
        name,
      }),
    createDashboard: (
      channelId: string,
      name: string,
      spec: Spec | null,
      templateId?: string,
    ) =>
      create.mutateAsync({
        channelId,
        name,
        spec: spec as Record<string, unknown> | null,
        templateId,
      }),
    deleteDashboard: (id: string) => remove.mutateAsync({ id }),
    // Ensure a channel has its home canvas (creating + seeding it if absent).
    // Idempotent server-side; returns the home canvas record.
    ensureHomeCanvas: (channelId: string) =>
      ensureHome.mutateAsync({ channelId }),
    // Explicitly persist a freeform canvas's current code + history (autosave
    // already runs each turn; this is the manual Save affordance).
    saveFreeformDashboard: (
      id: string,
      code: string,
      versions: FreeformVersion[],
      currentVersionId?: string,
    ) => saveFreeform.mutateAsync({ id, code, versions, currentVersionId }),
    // Fork a freeform canvas: create a fresh freeform record, then copy its
    // source + version history onto it. Returns the new record (to navigate to).
    forkFreeform: async (
      channelId: string,
      name: string,
      code: string,
      versions: FreeformVersion[],
      currentVersionId?: string,
    ): Promise<DashboardRecord> => {
      const record = await create.mutateAsync({
        channelId,
        name,
        spec: null,
        templateId: "freeform",
      });
      await saveFreeform.mutateAsync({
        id: record.id,
        code,
        versions,
        currentVersionId,
      });
      return record;
    },
    isSaving: save.isPending,
    isSavingFreeform: saveFreeform.isPending,
    isCreating: create.isPending,
    isDeleting: remove.isPending,
  };
}

/**
 * Open a channel's home canvas in the main content pane. Uses the channel's
 * known homeCanvasId when present; otherwise creates one on the fly (backfill
 * for channels made before home canvases existed) before navigating.
 */
export function useOpenHomeCanvas(): (channel: {
  id: string;
  homeCanvasId?: string;
}) => Promise<void> {
  const navigate = useNavigate();
  const { ensureHomeCanvas } = useDashboardMutations();

  return useCallback(
    async (channel) => {
      try {
        const dashboardId =
          channel.homeCanvasId ?? (await ensureHomeCanvas(channel.id)).id;
        await navigate({
          to: "/website/$channelId/dashboards/$dashboardId",
          params: { channelId: channel.id, dashboardId },
        });
      } catch (error) {
        log.error("Failed to open home canvas", { error });
        toast.error("Couldn't open channel home", {
          description: error instanceof Error ? error.message : String(error),
        });
      }
    },
    [navigate, ensureHomeCanvas],
  );
}

/** Create an empty canvas in a channel, enter edit mode, and navigate to it. */
export function useCreateAndOpenDashboard(
  channelId: string | undefined,
): (opts?: { templateId?: string; name?: string }) => Promise<void> {
  const navigate = useNavigate();
  const { createDashboard } = useDashboardMutations();
  const setEditing = useDashboardEditStore((s) => s.setEditing);
  const setTemplate = useCanvasChatStore((s) => s.setTemplate);

  return useCallback(
    async (opts) => {
      if (!channelId) return;
      const templateId = opts?.templateId ?? "dashboard";
      const name = opts?.name ?? "Untitled canvas";
      try {
        const record = await createDashboard(channelId, name, null, templateId);
        // Anchor the thread's agent to the chosen template before the first
        // message (WebsiteDashboard re-asserts it once the record loads).
        setTemplate(`dashboard:${record.id}`, templateId);
        setEditing(record.id, true);
        await navigate({
          to: "/website/$channelId/dashboards/$dashboardId",
          params: { channelId, dashboardId: record.id },
        });
      } catch (error) {
        log.error("Failed to create canvas", { error });
        toast.error("Couldn't create canvas", {
          description: error instanceof Error ? error.message : String(error),
        });
      }
    },
    [channelId, createDashboard, navigate, setEditing, setTemplate],
  );
}
